CREATE TABLE TRADE_BOARD_GAME
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    BGG_ID INTEGER NOT NULL,
    BGG_IMAGE_URL VARCHAR(255),
    BGG_THUMBNAIL_URL VARCHAR(255),
    TITLE VARCHAR(255),
    DESIGNER VARCHAR(255),
    IMAGE_URL VARCHAR(255),
    MAX_PLAYERS INTEGER NOT NULL,
    MIN_PLAYERS INTEGER NOT NULL,
    THUMBNAIL_URL VARCHAR(255),
    YEAR_PUBLISHED INTEGER NOT NULL
);
CREATE TABLE TRADE_BOARD_GAME_TITLE
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TITLE VARCHAR(255),
    TRADE_BOARD_GAME_ID BIGINT
);
CREATE TABLE TRADE_BOARD_GAME_TITLES
(
    TRADE_BOARD_GAME_ID BIGINT NOT NULL,
    TITLES_ID BIGINT NOT NULL
);
CREATE TABLE TRADE_ITEM
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    FOR_TRADE BOOLEAN NOT NULL,
    IMG_URL VARCHAR(255),
    TITLE VARCHAR(255) NOT NULL,
    OWNER_ID BIGINT NOT NULL
);
CREATE TABLE TRADE_USER
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    ROLE VARCHAR(255),
    USERNAME VARCHAR(255) NOT NULL
);
ALTER TABLE TRADE_BOARD_GAME_TITLE ADD FOREIGN KEY (TRADE_BOARD_GAME_ID) REFERENCES TRADE_BOARD_GAME (ID);
CREATE INDEX FK_25Q5OCJBA31IS4CUAWRPFQ8W3_INDEX_3 ON TRADE_BOARD_GAME_TITLE (TRADE_BOARD_GAME_ID);
ALTER TABLE TRADE_BOARD_GAME_TITLES ADD FOREIGN KEY (TRADE_BOARD_GAME_ID) REFERENCES TRADE_BOARD_GAME (ID);
ALTER TABLE TRADE_BOARD_GAME_TITLES ADD FOREIGN KEY (TITLES_ID) REFERENCES TRADE_BOARD_GAME_TITLE (ID);
CREATE UNIQUE INDEX UK_JREWHCGA0WPYWCQKPJDA72CH2_INDEX_7 ON TRADE_BOARD_GAME_TITLES (TITLES_ID);
CREATE INDEX FK_319SONVW0RI58SIKFC9159XYJ_INDEX_7 ON TRADE_BOARD_GAME_TITLES (TRADE_BOARD_GAME_ID);
ALTER TABLE TRADE_ITEM ADD FOREIGN KEY (OWNER_ID) REFERENCES TRADE_USER (ID);
CREATE INDEX FK_CUUFAG86DYBU3HSG2NICTC5RF_INDEX_8 ON TRADE_ITEM (OWNER_ID);
CREATE UNIQUE INDEX UK_FKJU7Q27EQVGM6PGDR4G6GXWB_INDEX_8 ON TRADE_USER (EMAIL);
CREATE UNIQUE INDEX UK_NYVDISKYB8ALJPVDMNCX6RF9G_INDEX_8 ON TRADE_USER (USERNAME);
