CREATE TABLE TRADE_BOARD_GAME_PROPERTIES
(
    PROPERTIES_ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TRADE_ITEM_ID BIGINT NOT NULL,
    BGG_ID INT,
    FOREIGN KEY (TRADE_ITEM_ID) REFERENCES TRADE_ITEM(ID)
);