CREATE TABLE WANT_LIST_ITEM
(
    OFFER_TRADE_ITEM_ID BIGINT NOT NULL,
    WANT_TRADE_ITEM_ID BIGINT NOT NULL,
    PRIORITY INT,
    PRIMARY KEY (OFFER_TRADE_ITEM_ID, WANT_TRADE_ITEM_ID),
    FOREIGN KEY (OFFER_TRADE_ITEM_ID) REFERENCES TRADE_ITEM(ID),
    FOREIGN KEY (WANT_TRADE_ITEM_ID) REFERENCES TRADE_ITEM(ID)
);