CREATE TABLE WANT_LIST
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TRADE_ITEM_ID BIGINT NOT NULL,
    FOREIGN KEY (TRADE_ITEM_ID) REFERENCES TRADE_ITEM(ID)
);

CREATE TABLE WANT_LIST_ENTRY
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    WANT_LIST_ID BIGINT NOT NULL,
    TRADE_ITEM_ID BIGINT NOT NULL,

    FOREIGN KEY (WANT_LIST_ID) REFERENCES WANT_LIST(ID),
    FOREIGN KEY (TRADE_ITEM_ID) REFERENCES TRADE_ITEM(ID)
);