CREATE TABLE GROUP_LIST
(
  ID    BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(255) NOT NULL UNIQUE
);

ALTER TABLE TRADE_ITEM ADD GROUP_LIST_ID BIGINT;
ALTER TABLE TRADE_ITEM ADD CONSTRAINT FK_GROUP_LIST_ID FOREIGN KEY (GROUP_LIST_ID) REFERENCES GROUP_LIST (ID);