CREATE TABLE ITEM_GROUP
(
  ID    BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(255) NOT NULL UNIQUE
);

ALTER TABLE TRADE_ITEM ADD ITEM_GROUP_ID BIGINT;
ALTER TABLE TRADE_ITEM ADD CONSTRAINT FK_GROUP_LIST_ID FOREIGN KEY (ITEM_GROUP_ID) REFERENCES ITEM_GROUP (ID);