DELETE FROM ITEM_GROUP;
DROP TABLE ITEM_GROUP;

ALTER TABLE TRADE_ITEM MODIFY OWNER_ID BIGINT NULL;
ALTER TABLE TRADE_ITEM MODIFY DESCRIPTION VARCHAR(255) NULL;
ALTER TABLE TRADE_ITEM DROP COLUMN FOR_TRADE;
